FROM alpine:3.12.0

ENV TZ='Asia/Tokyo'

RUN apk update \
  && apk add --no-cache \
    tzdata \
    sudo \
    git \
    curl \
    gcc \
    g++ \
    libc-dev \
    make \
    cmake \
    clang \
    gdb \
  && rm -rf /var/cache/apk/*

RUN echo "${TZ}" > /etc/timezone \
  && rm -f /etc/localtime \
  && ln -s /usr/share/zoneinfo/Asia/Tokyo /etc/localtime

CMD ["/bin/ash"]

