version: '3.7'
services:
  jupyter:
    image: ktsuda/juypter:latest
    build: .
    container_name: jupyter
    volumes:
      - ./work:/work
    ports:
      - "8888:8888"
    command: "poetry run jupyter notebook --no-browser --ip=0.0.0.0 --port=8888 --allow-root --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.disable_check_xsrf=True"
